// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"context"

	"github.com/google/uuid"
	entity "github.com/mamadeusia/RequestSrv/entity"
)

type Querier interface {
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Requests, error)
	GetCountRequestCollaboratorsByAdminID(ctx context.Context, adminID int64) (int64, error)
	GetOrphanRequests(ctx context.Context, arg GetOrphanRequestsParams) ([]Requests, error)
	GetRequestByID(ctx context.Context, id uuid.UUID) (Requests, error)
	GetRequestByRequesterID(ctx context.Context, arg GetRequestByRequesterIDParams) ([]Requests, error)
	GetRequestCollaboratorsByAdminID(ctx context.Context, arg GetRequestCollaboratorsByAdminIDParams) ([]RequestCollaborators, error)
	GetRequestQuestionAnswers(ctx context.Context, id uuid.UUID) (entity.QuestionAnswerSlice, error)
	UpdateRequestColloboratorsAdmin(ctx context.Context, arg UpdateRequestColloboratorsAdminParams) error
	UpdateRequestColloboratorsValidators(ctx context.Context, arg UpdateRequestColloboratorsValidatorsParams) error
	UpdateRequestQuestionAnswers(ctx context.Context, arg UpdateRequestQuestionAnswersParams) error
	UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error
}

var _ Querier = (*Queries)(nil)
