// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/RequestSrv.proto

package RequestSrv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_StatusFilling                    Status = 0
	Status_StatusFilled                     Status = 1
	Status_StatusUncompleted                Status = 2
	Status_StatusAdminPending               Status = 3
	Status_StatusAdminChecking              Status = 4
	Status_StatusAdminAsk                   Status = 5
	Status_StatusRequesterAdminResponse     Status = 6
	Status_StatusValidatorsChecking         Status = 7
	Status_StatusRequesterValidatorResponse Status = 8
	Status_StatusBlockchainPending          Status = 9
	Status_StatusRejected                   Status = 10
	Status_StatusApproved                   Status = 11
	Status_StatusValidatorQuestionReady     Status = 12
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0:  "StatusFilling",
		1:  "StatusFilled",
		2:  "StatusUncompleted",
		3:  "StatusAdminPending",
		4:  "StatusAdminChecking",
		5:  "StatusAdminAsk",
		6:  "StatusRequesterAdminResponse",
		7:  "StatusValidatorsChecking",
		8:  "StatusRequesterValidatorResponse",
		9:  "StatusBlockchainPending",
		10: "StatusRejected",
		11: "StatusApproved",
		12: "StatusValidatorQuestionReady",
	}
	Status_value = map[string]int32{
		"StatusFilling":                    0,
		"StatusFilled":                     1,
		"StatusUncompleted":                2,
		"StatusAdminPending":               3,
		"StatusAdminChecking":              4,
		"StatusAdminAsk":                   5,
		"StatusRequesterAdminResponse":     6,
		"StatusValidatorsChecking":         7,
		"StatusRequesterValidatorResponse": 8,
		"StatusBlockchainPending":          9,
		"StatusRejected":                   10,
		"StatusApproved":                   11,
		"StatusValidatorQuestionReady":     12,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_RequestSrv_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_RequestSrv_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{0}
}

type GetOrphanRequestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetOrphanRequestsRequest) Reset() {
	*x = GetOrphanRequestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrphanRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrphanRequestsRequest) ProtoMessage() {}

func (x *GetOrphanRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrphanRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetOrphanRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrphanRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrphanRequestsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetOrphanRequestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*Request `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *GetOrphanRequestsResponse) Reset() {
	*x = GetOrphanRequestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrphanRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrphanRequestsResponse) ProtoMessage() {}

func (x *GetOrphanRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrphanRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetOrphanRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrphanRequestsResponse) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type StoredMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatID    int64 `protobuf:"varint,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	MessageID int32 `protobuf:"varint,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
}

func (x *StoredMessage) Reset() {
	*x = StoredMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredMessage) ProtoMessage() {}

func (x *StoredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredMessage.ProtoReflect.Descriptor instead.
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{2}
}

func (x *StoredMessage) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

func (x *StoredMessage) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RequesterID     int64             `protobuf:"varint,2,opt,name=requesterID,proto3" json:"requesterID,omitempty"`
	FullName        string            `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Age             int32             `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	LocationLat     float64           `protobuf:"fixed64,5,opt,name=locationLat,proto3" json:"locationLat,omitempty"`
	LocationLon     float64           `protobuf:"fixed64,6,opt,name=locationLon,proto3" json:"locationLon,omitempty"`
	Photo           *StoredMessage    `protobuf:"bytes,7,opt,name=photo,proto3" json:"photo,omitempty"`
	Msgs            []*StoredMessage  `protobuf:"bytes,8,rep,name=msgs,proto3" json:"msgs,omitempty"`
	QuestionAnswers []*QuestionAnswer `protobuf:"bytes,9,rep,name=questionAnswers,proto3" json:"questionAnswers,omitempty"`
	Status          Status            `protobuf:"varint,10,opt,name=status,proto3,enum=RequestSrv.Status" json:"status,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Request) GetRequesterID() int64 {
	if x != nil {
		return x.RequesterID
	}
	return 0
}

func (x *Request) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Request) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Request) GetLocationLat() float64 {
	if x != nil {
		return x.LocationLat
	}
	return 0
}

func (x *Request) GetLocationLon() float64 {
	if x != nil {
		return x.LocationLon
	}
	return 0
}

func (x *Request) GetPhoto() *StoredMessage {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *Request) GetMsgs() []*StoredMessage {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *Request) GetQuestionAnswers() []*QuestionAnswer {
	if x != nil {
		return x.QuestionAnswers
	}
	return nil
}

func (x *Request) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_StatusFilling
}

type CreateRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterID int64            `protobuf:"varint,1,opt,name=requesterID,proto3" json:"requesterID,omitempty"`
	FullName    string           `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Age         int32            `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	LocationLat float64          `protobuf:"fixed64,4,opt,name=locationLat,proto3" json:"locationLat,omitempty"`
	LocationLon float64          `protobuf:"fixed64,5,opt,name=locationLon,proto3" json:"locationLon,omitempty"`
	Photo       *StoredMessage   `protobuf:"bytes,6,opt,name=photo,proto3" json:"photo,omitempty"`
	Msgs        []*StoredMessage `protobuf:"bytes,7,rep,name=msgs,proto3" json:"msgs,omitempty"`
	Status      Status           `protobuf:"varint,8,opt,name=status,proto3,enum=RequestSrv.Status" json:"status,omitempty"`
}

func (x *CreateRequestRequest) Reset() {
	*x = CreateRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestRequest) ProtoMessage() {}

func (x *CreateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequestRequest) GetRequesterID() int64 {
	if x != nil {
		return x.RequesterID
	}
	return 0
}

func (x *CreateRequestRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateRequestRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateRequestRequest) GetLocationLat() float64 {
	if x != nil {
		return x.LocationLat
	}
	return 0
}

func (x *CreateRequestRequest) GetLocationLon() float64 {
	if x != nil {
		return x.LocationLon
	}
	return 0
}

func (x *CreateRequestRequest) GetPhoto() *StoredMessage {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *CreateRequestRequest) GetMsgs() []*StoredMessage {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *CreateRequestRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_StatusFilling
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequestResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetRequestByAdminIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminID int64 `protobuf:"varint,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	Limit   int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetRequestByAdminIDRequest) Reset() {
	*x = GetRequestByAdminIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestByAdminIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestByAdminIDRequest) ProtoMessage() {}

func (x *GetRequestByAdminIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestByAdminIDRequest.ProtoReflect.Descriptor instead.
func (*GetRequestByAdminIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequestByAdminIDRequest) GetAdminID() int64 {
	if x != nil {
		return x.AdminID
	}
	return 0
}

func (x *GetRequestByAdminIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRequestByAdminIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRequestByAdminIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int32      `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Requests []*Request `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *GetRequestByAdminIDResponse) Reset() {
	*x = GetRequestByAdminIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestByAdminIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestByAdminIDResponse) ProtoMessage() {}

func (x *GetRequestByAdminIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestByAdminIDResponse.ProtoReflect.Descriptor instead.
func (*GetRequestByAdminIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequestByAdminIDResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetRequestByAdminIDResponse) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type GetRequestByRequesterIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterID int64 `protobuf:"varint,1,opt,name=requesterID,proto3" json:"requesterID,omitempty"`
	Limit       int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset      int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetRequestByRequesterIDRequest) Reset() {
	*x = GetRequestByRequesterIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestByRequesterIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestByRequesterIDRequest) ProtoMessage() {}

func (x *GetRequestByRequesterIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestByRequesterIDRequest.ProtoReflect.Descriptor instead.
func (*GetRequestByRequesterIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{8}
}

func (x *GetRequestByRequesterIDRequest) GetRequesterID() int64 {
	if x != nil {
		return x.RequesterID
	}
	return 0
}

func (x *GetRequestByRequesterIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRequestByRequesterIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRequestByRequesterIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *GetRequestByRequesterIDResponse) Reset() {
	*x = GetRequestByRequesterIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestByRequesterIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestByRequesterIDResponse) ProtoMessage() {}

func (x *GetRequestByRequesterIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestByRequesterIDResponse.ProtoReflect.Descriptor instead.
func (*GetRequestByRequesterIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{9}
}

func (x *GetRequestByRequesterIDResponse) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type UpdateRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Status    Status `protobuf:"varint,2,opt,name=status,proto3,enum=RequestSrv.Status" json:"status,omitempty"`
}

func (x *UpdateRequestRequest) Reset() {
	*x = UpdateRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestRequest) ProtoMessage() {}

func (x *UpdateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRequestRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *UpdateRequestRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_StatusFilling
}

type UpdateRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UpdateRequestResponse) Reset() {
	*x = UpdateRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestResponse) ProtoMessage() {}

func (x *UpdateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestResponse.ProtoReflect.Descriptor instead.
func (*UpdateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRequestResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetRequestsByPersonIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonID int64 `protobuf:"varint,1,opt,name=personID,proto3" json:"personID,omitempty"`
}

func (x *GetRequestsByPersonIDRequest) Reset() {
	*x = GetRequestsByPersonIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestsByPersonIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestsByPersonIDRequest) ProtoMessage() {}

func (x *GetRequestsByPersonIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestsByPersonIDRequest.ProtoReflect.Descriptor instead.
func (*GetRequestsByPersonIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{12}
}

func (x *GetRequestsByPersonIDRequest) GetPersonID() int64 {
	if x != nil {
		return x.PersonID
	}
	return 0
}

type GetRequestsByPersonIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *GetRequestsByPersonIDResponse) Reset() {
	*x = GetRequestsByPersonIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestsByPersonIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestsByPersonIDResponse) ProtoMessage() {}

func (x *GetRequestsByPersonIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestsByPersonIDResponse.ProtoReflect.Descriptor instead.
func (*GetRequestsByPersonIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{13}
}

func (x *GetRequestsByPersonIDResponse) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type SetAdminForRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	AdminID   int64  `protobuf:"varint,2,opt,name=adminID,proto3" json:"adminID,omitempty"`
}

func (x *SetAdminForRequestRequest) Reset() {
	*x = SetAdminForRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAdminForRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminForRequestRequest) ProtoMessage() {}

func (x *SetAdminForRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminForRequestRequest.ProtoReflect.Descriptor instead.
func (*SetAdminForRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{14}
}

func (x *SetAdminForRequestRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *SetAdminForRequestRequest) GetAdminID() int64 {
	if x != nil {
		return x.AdminID
	}
	return 0
}

type SetAdminForRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SetAdminForRequestResponse) Reset() {
	*x = SetAdminForRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAdminForRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminForRequestResponse) ProtoMessage() {}

func (x *SetAdminForRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminForRequestResponse.ProtoReflect.Descriptor instead.
func (*SetAdminForRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{15}
}

func (x *SetAdminForRequestResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SetValidatorsForRequestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
}

func (x *SetValidatorsForRequestRequest) Reset() {
	*x = SetValidatorsForRequestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValidatorsForRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValidatorsForRequestRequest) ProtoMessage() {}

func (x *SetValidatorsForRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValidatorsForRequestRequest.ProtoReflect.Descriptor instead.
func (*SetValidatorsForRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{16}
}

func (x *SetValidatorsForRequestRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type SetValidatorsForRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SetValidatorsForRequestResponse) Reset() {
	*x = SetValidatorsForRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValidatorsForRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValidatorsForRequestResponse) ProtoMessage() {}

func (x *SetValidatorsForRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValidatorsForRequestResponse.ProtoReflect.Descriptor instead.
func (*SetValidatorsForRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{17}
}

func (x *SetValidatorsForRequestResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendPotentialValidatorsNotificationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
}

func (x *SendPotentialValidatorsNotificationsRequest) Reset() {
	*x = SendPotentialValidatorsNotificationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPotentialValidatorsNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPotentialValidatorsNotificationsRequest) ProtoMessage() {}

func (x *SendPotentialValidatorsNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPotentialValidatorsNotificationsRequest.ProtoReflect.Descriptor instead.
func (*SendPotentialValidatorsNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{18}
}

func (x *SendPotentialValidatorsNotificationsRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type SendPotentialValidatorsNotificationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendPotentialValidatorsNotificationsResponse) Reset() {
	*x = SendPotentialValidatorsNotificationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPotentialValidatorsNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPotentialValidatorsNotificationsResponse) ProtoMessage() {}

func (x *SendPotentialValidatorsNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPotentialValidatorsNotificationsResponse.ProtoReflect.Descriptor instead.
func (*SendPotentialValidatorsNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{19}
}

func (x *SendPotentialValidatorsNotificationsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetCountRequestByAdminIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminID int64 `protobuf:"varint,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
}

func (x *GetCountRequestByAdminIDRequest) Reset() {
	*x = GetCountRequestByAdminIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountRequestByAdminIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountRequestByAdminIDRequest) ProtoMessage() {}

func (x *GetCountRequestByAdminIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountRequestByAdminIDRequest.ProtoReflect.Descriptor instead.
func (*GetCountRequestByAdminIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{20}
}

func (x *GetCountRequestByAdminIDRequest) GetAdminID() int64 {
	if x != nil {
		return x.AdminID
	}
	return 0
}

type GetCountRequestByAdminIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestCounter int64 `protobuf:"varint,1,opt,name=requestCounter,proto3" json:"requestCounter,omitempty"`
	PendingCounter int64 `protobuf:"varint,2,opt,name=PendingCounter,proto3" json:"PendingCounter,omitempty"`
}

func (x *GetCountRequestByAdminIDResponse) Reset() {
	*x = GetCountRequestByAdminIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCountRequestByAdminIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountRequestByAdminIDResponse) ProtoMessage() {}

func (x *GetCountRequestByAdminIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountRequestByAdminIDResponse.ProtoReflect.Descriptor instead.
func (*GetCountRequestByAdminIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{21}
}

func (x *GetCountRequestByAdminIDResponse) GetRequestCounter() int64 {
	if x != nil {
		return x.RequestCounter
	}
	return 0
}

func (x *GetCountRequestByAdminIDResponse) GetPendingCounter() int64 {
	if x != nil {
		return x.PendingCounter
	}
	return 0
}

type QuestionAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question string           `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answers  []*StoredMessage `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *QuestionAnswer) Reset() {
	*x = QuestionAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAnswer) ProtoMessage() {}

func (x *QuestionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAnswer.ProtoReflect.Descriptor instead.
func (*QuestionAnswer) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{22}
}

func (x *QuestionAnswer) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QuestionAnswer) GetAnswers() []*StoredMessage {
	if x != nil {
		return x.Answers
	}
	return nil
}

type AddQuestionAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string           `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Question  string           `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answers   []*StoredMessage `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *AddQuestionAnswerRequest) Reset() {
	*x = AddQuestionAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionAnswerRequest) ProtoMessage() {}

func (x *AddQuestionAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionAnswerRequest.ProtoReflect.Descriptor instead.
func (*AddQuestionAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{23}
}

func (x *AddQuestionAnswerRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *AddQuestionAnswerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AddQuestionAnswerRequest) GetAnswers() []*StoredMessage {
	if x != nil {
		return x.Answers
	}
	return nil
}

type AddQuestionAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddQuestionAnswerResponse) Reset() {
	*x = AddQuestionAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionAnswerResponse) ProtoMessage() {}

func (x *AddQuestionAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionAnswerResponse.ProtoReflect.Descriptor instead.
func (*AddQuestionAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{24}
}

func (x *AddQuestionAnswerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetQuestionAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
}

func (x *GetQuestionAnswerRequest) Reset() {
	*x = GetQuestionAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionAnswerRequest) ProtoMessage() {}

func (x *GetQuestionAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionAnswerRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{25}
}

func (x *GetQuestionAnswerRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type GetQuestionAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*QuestionAnswer `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *GetQuestionAnswerResponse) Reset() {
	*x = GetQuestionAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RequestSrv_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionAnswerResponse) ProtoMessage() {}

func (x *GetQuestionAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RequestSrv_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionAnswerResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_RequestSrv_proto_rawDescGZIP(), []int{26}
}

func (x *GetQuestionAnswerResponse) GetResult() []*QuestionAnswer {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_RequestSrv_proto protoreflect.FileDescriptor

var file_proto_RequestSrv_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53,
	0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x72, 0x76, 0x22, 0x48, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x70, 0x68, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x4c,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x70, 0x68, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x0d,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x44, 0x22, 0xff, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x12, 0x2d, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6d,
	0x73, 0x67, 0x73, 0x12, 0x44, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x0f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb6, 0x02, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x12, 0x2d, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6d, 0x73,
	0x67, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x64, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22,
	0x64, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x72, 0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x70, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x52, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x60, 0x0a, 0x14, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x44, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29, 0x0a,
	0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x42, 0x79, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x49, 0x44, 0x22, 0x50, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x42, 0x79, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x72, 0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x53, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x1a, 0x53,
	0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3e, 0x0a, 0x1e, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x46, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x22, 0x33, 0x0a, 0x1f, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x46, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x4b, 0x0a, 0x2b, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x22, 0x40, 0x0a,
	0x2c, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x3b, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x72, 0x0a, 0x20,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x22, 0x61, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33,
	0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x07, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x22,
	0x2d, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x38,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x22, 0x4f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53,
	0x72, 0x76, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0xd6, 0x02, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x69,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x02,
	0x12, 0x16, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x10,
	0x04, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x41, 0x73, 0x6b, 0x10, 0x05, 0x12, 0x20, 0x0a, 0x1c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x06, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x10, 0x07, 0x12, 0x24, 0x0a, 0x20, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x08, 0x12, 0x1b, 0x0a, 0x17, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x09, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x0a, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x10, 0x0b,
	0x12, 0x20, 0x0a, 0x1c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x10, 0x0c, 0x32, 0xbc, 0x09, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72,
	0x76, 0x12, 0x56, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72,
	0x76, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x12, 0x53, 0x65, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x46, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x74, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x26, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53,
	0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x74, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2a, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x9b,
	0x01, 0x0a, 0x24, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x37, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x38, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x50, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x77, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x2b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53,
	0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x70, 0x68,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x70, 0x68, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x70, 0x68, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x41, 0x64, 0x64,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x24,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x41, 0x64, 0x64, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72,
	0x76, 0x2e, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x12, 0x24, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x2e,
	0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x72, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_RequestSrv_proto_rawDescOnce sync.Once
	file_proto_RequestSrv_proto_rawDescData = file_proto_RequestSrv_proto_rawDesc
)

func file_proto_RequestSrv_proto_rawDescGZIP() []byte {
	file_proto_RequestSrv_proto_rawDescOnce.Do(func() {
		file_proto_RequestSrv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_RequestSrv_proto_rawDescData)
	})
	return file_proto_RequestSrv_proto_rawDescData
}

var file_proto_RequestSrv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_RequestSrv_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_RequestSrv_proto_goTypes = []interface{}{
	(Status)(0),                                          // 0: RequestSrv.Status
	(*GetOrphanRequestsRequest)(nil),                     // 1: RequestSrv.GetOrphanRequestsRequest
	(*GetOrphanRequestsResponse)(nil),                    // 2: RequestSrv.GetOrphanRequestsResponse
	(*StoredMessage)(nil),                                // 3: RequestSrv.StoredMessage
	(*Request)(nil),                                      // 4: RequestSrv.Request
	(*CreateRequestRequest)(nil),                         // 5: RequestSrv.CreateRequestRequest
	(*CreateRequestResponse)(nil),                        // 6: RequestSrv.CreateRequestResponse
	(*GetRequestByAdminIDRequest)(nil),                   // 7: RequestSrv.GetRequestByAdminIDRequest
	(*GetRequestByAdminIDResponse)(nil),                  // 8: RequestSrv.GetRequestByAdminIDResponse
	(*GetRequestByRequesterIDRequest)(nil),               // 9: RequestSrv.GetRequestByRequesterIDRequest
	(*GetRequestByRequesterIDResponse)(nil),              // 10: RequestSrv.GetRequestByRequesterIDResponse
	(*UpdateRequestRequest)(nil),                         // 11: RequestSrv.UpdateRequestRequest
	(*UpdateRequestResponse)(nil),                        // 12: RequestSrv.UpdateRequestResponse
	(*GetRequestsByPersonIDRequest)(nil),                 // 13: RequestSrv.GetRequestsByPersonIDRequest
	(*GetRequestsByPersonIDResponse)(nil),                // 14: RequestSrv.GetRequestsByPersonIDResponse
	(*SetAdminForRequestRequest)(nil),                    // 15: RequestSrv.SetAdminForRequestRequest
	(*SetAdminForRequestResponse)(nil),                   // 16: RequestSrv.SetAdminForRequestResponse
	(*SetValidatorsForRequestRequest)(nil),               // 17: RequestSrv.SetValidatorsForRequestRequest
	(*SetValidatorsForRequestResponse)(nil),              // 18: RequestSrv.SetValidatorsForRequestResponse
	(*SendPotentialValidatorsNotificationsRequest)(nil),  // 19: RequestSrv.SendPotentialValidatorsNotificationsRequest
	(*SendPotentialValidatorsNotificationsResponse)(nil), // 20: RequestSrv.SendPotentialValidatorsNotificationsResponse
	(*GetCountRequestByAdminIDRequest)(nil),              // 21: RequestSrv.GetCountRequestByAdminIDRequest
	(*GetCountRequestByAdminIDResponse)(nil),             // 22: RequestSrv.GetCountRequestByAdminIDResponse
	(*QuestionAnswer)(nil),                               // 23: RequestSrv.QuestionAnswer
	(*AddQuestionAnswerRequest)(nil),                     // 24: RequestSrv.AddQuestionAnswerRequest
	(*AddQuestionAnswerResponse)(nil),                    // 25: RequestSrv.AddQuestionAnswerResponse
	(*GetQuestionAnswerRequest)(nil),                     // 26: RequestSrv.GetQuestionAnswerRequest
	(*GetQuestionAnswerResponse)(nil),                    // 27: RequestSrv.GetQuestionAnswerResponse
}
var file_proto_RequestSrv_proto_depIdxs = []int32{
	4,  // 0: RequestSrv.GetOrphanRequestsResponse.requests:type_name -> RequestSrv.Request
	3,  // 1: RequestSrv.Request.photo:type_name -> RequestSrv.StoredMessage
	3,  // 2: RequestSrv.Request.msgs:type_name -> RequestSrv.StoredMessage
	23, // 3: RequestSrv.Request.questionAnswers:type_name -> RequestSrv.QuestionAnswer
	0,  // 4: RequestSrv.Request.status:type_name -> RequestSrv.Status
	3,  // 5: RequestSrv.CreateRequestRequest.photo:type_name -> RequestSrv.StoredMessage
	3,  // 6: RequestSrv.CreateRequestRequest.msgs:type_name -> RequestSrv.StoredMessage
	0,  // 7: RequestSrv.CreateRequestRequest.status:type_name -> RequestSrv.Status
	4,  // 8: RequestSrv.GetRequestByAdminIDResponse.requests:type_name -> RequestSrv.Request
	4,  // 9: RequestSrv.GetRequestByRequesterIDResponse.requests:type_name -> RequestSrv.Request
	0,  // 10: RequestSrv.UpdateRequestRequest.status:type_name -> RequestSrv.Status
	4,  // 11: RequestSrv.GetRequestsByPersonIDResponse.requests:type_name -> RequestSrv.Request
	3,  // 12: RequestSrv.QuestionAnswer.answers:type_name -> RequestSrv.StoredMessage
	3,  // 13: RequestSrv.AddQuestionAnswerRequest.answers:type_name -> RequestSrv.StoredMessage
	23, // 14: RequestSrv.GetQuestionAnswerResponse.result:type_name -> RequestSrv.QuestionAnswer
	5,  // 15: RequestSrv.RequestSrv.CreateRequest:input_type -> RequestSrv.CreateRequestRequest
	15, // 16: RequestSrv.RequestSrv.SetAdminForRequest:input_type -> RequestSrv.SetAdminForRequestRequest
	17, // 17: RequestSrv.RequestSrv.SetValidatorsForRequest:input_type -> RequestSrv.SetValidatorsForRequestRequest
	7,  // 18: RequestSrv.RequestSrv.GetRequestByAdminID:input_type -> RequestSrv.GetRequestByAdminIDRequest
	9,  // 19: RequestSrv.RequestSrv.GetRequestByRequesterID:input_type -> RequestSrv.GetRequestByRequesterIDRequest
	11, // 20: RequestSrv.RequestSrv.UpdateRequest:input_type -> RequestSrv.UpdateRequestRequest
	19, // 21: RequestSrv.RequestSrv.SendPotentialValidatorsNotifications:input_type -> RequestSrv.SendPotentialValidatorsNotificationsRequest
	21, // 22: RequestSrv.RequestSrv.GetCountRequestByAdminID:input_type -> RequestSrv.GetCountRequestByAdminIDRequest
	1,  // 23: RequestSrv.RequestSrv.GetOrphanRequests:input_type -> RequestSrv.GetOrphanRequestsRequest
	24, // 24: RequestSrv.RequestSrv.AddQuestionAnswer:input_type -> RequestSrv.AddQuestionAnswerRequest
	26, // 25: RequestSrv.RequestSrv.GetQuestionAnswer:input_type -> RequestSrv.GetQuestionAnswerRequest
	6,  // 26: RequestSrv.RequestSrv.CreateRequest:output_type -> RequestSrv.CreateRequestResponse
	16, // 27: RequestSrv.RequestSrv.SetAdminForRequest:output_type -> RequestSrv.SetAdminForRequestResponse
	18, // 28: RequestSrv.RequestSrv.SetValidatorsForRequest:output_type -> RequestSrv.SetValidatorsForRequestResponse
	8,  // 29: RequestSrv.RequestSrv.GetRequestByAdminID:output_type -> RequestSrv.GetRequestByAdminIDResponse
	10, // 30: RequestSrv.RequestSrv.GetRequestByRequesterID:output_type -> RequestSrv.GetRequestByRequesterIDResponse
	12, // 31: RequestSrv.RequestSrv.UpdateRequest:output_type -> RequestSrv.UpdateRequestResponse
	20, // 32: RequestSrv.RequestSrv.SendPotentialValidatorsNotifications:output_type -> RequestSrv.SendPotentialValidatorsNotificationsResponse
	22, // 33: RequestSrv.RequestSrv.GetCountRequestByAdminID:output_type -> RequestSrv.GetCountRequestByAdminIDResponse
	2,  // 34: RequestSrv.RequestSrv.GetOrphanRequests:output_type -> RequestSrv.GetOrphanRequestsResponse
	25, // 35: RequestSrv.RequestSrv.AddQuestionAnswer:output_type -> RequestSrv.AddQuestionAnswerResponse
	27, // 36: RequestSrv.RequestSrv.GetQuestionAnswer:output_type -> RequestSrv.GetQuestionAnswerResponse
	26, // [26:37] is the sub-list for method output_type
	15, // [15:26] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_RequestSrv_proto_init() }
func file_proto_RequestSrv_proto_init() {
	if File_proto_RequestSrv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_RequestSrv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrphanRequestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrphanRequestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoredMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestByAdminIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestByAdminIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestByRequesterIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestByRequesterIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestsByPersonIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestsByPersonIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAdminForRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAdminForRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValidatorsForRequestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValidatorsForRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPotentialValidatorsNotificationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPotentialValidatorsNotificationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountRequestByAdminIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCountRequestByAdminIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RequestSrv_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_RequestSrv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_RequestSrv_proto_goTypes,
		DependencyIndexes: file_proto_RequestSrv_proto_depIdxs,
		EnumInfos:         file_proto_RequestSrv_proto_enumTypes,
		MessageInfos:      file_proto_RequestSrv_proto_msgTypes,
	}.Build()
	File_proto_RequestSrv_proto = out.File
	file_proto_RequestSrv_proto_rawDesc = nil
	file_proto_RequestSrv_proto_goTypes = nil
	file_proto_RequestSrv_proto_depIdxs = nil
}
